CREATE ROLE DBT_ROLE;

CREATE USER DBT_USR
PASSWORD = '*******'
DEFAULT_ROLE = DBT_ROLE
DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE DBT_ROLE TO USER DBT_USR;

SHOW USERS;

GRANT ROLE DBT_ROLE TO ROLE ACCOUNTADMIN;
-------------------------------------------


CREATE DATABASE IF NOT EXISTS MOVIELENS;
USE DATABASE MOVIELENS;
CREATE SCHEMA IF NOT EXISTS RAW;

USE ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE MOVIELENS TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA MOVIELENS.GIT TO ROLE DBT_ROLE;
GRANT ALL ON SCHEMA MOVIELENS.RAW TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE MOVIELENS TO ROLE DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA MOVIELENS.RAW TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA MOVIELENS.RAW TO ROLE DBT_ROLE;
--------------------------------------------------------------------

SHOW STORAGE INTEGRATIONS;

CREATE OR REPLACE STORAGE INTEGRATION S3_MOVIELENS_INTEGRATION
TYPE=EXTERNAL_STAGE
ENABLED = TRUE
STORAGE_PROVIDER='S3'
STORAGE_AWS_ROLE_ARN='arn:aws:iam::334360387642:role/snowrole'
STORAGE_ALLOWED_LOCATIONS=('s3://amzn-movielens-dataset/')

DESC STORAGE INTEGRATION S3_MOVIELENS_INTEGRATION

CREATE OR REPLACE STAGE S3_MOVIELENS_STAGE
URL='s3://amzn-movielens-dataset'
STORAGE_INTEGRATION= S3_MOVIELENS_INTEGRATION


ALTER STAGE S3_MOVIELENS_STAGE
SET FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1);

ls @S3_MOVIELENS_STAGE

ALTER STAGE S3_MOVIELENS_STAGE
SET
DIRECTORY=(ENABLE=TRUE)
 
ALTER STAGE S3_MOVIELENS_STAGE REFRESH;

ls @S3_MOVIELENS_STAGE;

SELECT * FROM DIRECTORY(@S3_MOVIELENS_STAGE);

------------------------------------------------------------------

CREATE OR REPLACE TABLE LINKS (
    MOVIEID int,
    IMDBID int,
    TMDBID int
);


COPY INTO LINKS
FROM @S3_MOVIELENS_STAGE
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
FILES = ('links.csv');

DESC STAGE S3_MOVIELENS_STAGE;

SELECT TOP 5 * FROM LINKS;

------------------------------------------------
CREATE OR REPLACE TABLE MOVIES (
    MOVIEID NUMBER(38,0) NOT NULL,
    TITLE STRING,
    GENRES STRING
)

COPY INTO MOVIES
FROM '@S3_MOVIELENS_STAGE/movies.csv'
FILE_FORMAT=(FORMAT_NAME=MOVIES_CSV_FORMAT)
------------------------------------------------
CREATE OR REPLACE TABLE ratings (
    userId INTEGER,
    movieId INTEGER,
    rating FLOAT,
    timestamp TIMESTAMP_NTZ
);

ls @S3_MOVIELENS_STAGE

COPY INTO ratings
FROM '@S3_MOVIELENS_STAGE/ratings.csv'
FILE_FORMAT=(FORMAT_NAME=MOVIES_CSV_FORMAT)
------------------------------------------------

CREATE OR REPLACE TABLE MOVIE_TAGS (
    USERID      NUMBER,
    MOVIEID     NUMBER,
    TAG         STRING,
    "TIMESTAMP" TIMESTAMP_NTZ
);

desc table MOVIE_TAGS 

COPY INTO MOVIE_TAGS
FROM '@S3_MOVIELENS_STAGE/tags.csv'
FILE_FORMAT = (FORMAT_NAME=MOVIES_CSV_FORMAT)
ON_ERROR = 'CONTINUE';

------------------------------------------------
SELECT 
    'ALTER TABLE RAW.' || table_name || 
    ' RENAME TO RAW.raw_' || table_name
FROM information_schema.tables
WHERE table_schema = 'RAW';

ALTER TABLE RAW.GENOME_TAGS RENAME TO RAW.raw_GENOME_TAGS;
ALTER TABLE RAW.GENOME_SCORES RENAME TO RAW.raw_GENOME_SCORES;
ALTER TABLE RAW.RATINGS RENAME TO RAW.raw_RATINGS;
ALTER TABLE RAW.LINKS RENAME TO RAW.raw_LINKS;
ALTER TABLE RAW.MOVIE_TAGS RENAME TO RAW.raw_MOVIE_TAGS;
ALTER TABLE RAW.MOVIES RENAME TO RAW.raw_MOVIES;
------------------------------------------------------


--GIT INTEGRATION -NOT NEED AND JUST FOR REFERENCE
CREATE SCHEMA GIT;


CREATE OR REPLACE SECRET scrt_github
  TYPE = PASSWORD
  USERNAME = 'RakshithNayak2023'
  PASSWORD = '******';

GRANT READ ON SECRET scrt_github TO ROLE dbt_role;
GRANT USAGE ON SECRET MOVIELENS.GIT.scrt_github TO ROLE DBT_ROLE;

CREATE OR REPLACE API INTEGRATION git_integration
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/RakshithNayak2023')
  ALLOWED_AUTHENTICATION_SECRETS=(scrt_github)
  ENABLED = TRUE;


CREATE OR REPLACE GIT REPOSITORY snowflake_movielens_analysis
  API_INTEGRATION = git_integration
  GIT_CREDENTIALS=scrt_github
  ORIGIN = 'https://github.com/RakshithNayak2023/snowflake_movielens_analysis';

  
GRANT READ ON GIT REPOSITORY snowflake_movielens_analysis TO ROLE DBT_ROLE;
GRANT WRITE ON GIT REPOSITORY snowflake_movielens_analysis TO ROLE DBT_ROLE;
GRANT USAGE ON INTEGRATION git_integration TO ROLE DBT_ROLE;

DESC SECRET scrt_github;
DESC INTEGRATION git_integration;

ALTER GIT REPOSITORY snowflake_movielens_analysis FETCH;

ls '@snowflake_movielens_analysis/branches/featurebranch_RakshithNayak2023/'

-----------------------------------------------




