USE ROLE ACCOUNTADMIN;
USE MYDB.MYSCHEMA;

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER,
    NAME STRING,
    AGE NUMBER,
    CITY STRING
);

CREATE OR REPLACE STREAM CUSTOMER_STREAM
ON TABLE CUSTOMERS; 

select * from customers

DELETE FROM customers WHERE CUSTOMER_ID = 4;

UPDATE CUSTOMERS
SET CITY = 'goy'
WHERE CUSTOMER_ID = 1;

INSERT INTO CUSTOMERS VALUES --(5, 'Mom', 20, 'MIZORAM'),
(1, 'Kirana', 22, 'Bangalore'),
(2, 'Ravi', 30, 'Mysore'),
(3, 'Ricky', 20, 'Udupi');

SELECT * FROM MYSCHEMA.CUSTOMER_STREAM;

delete from  CUSTOMERS
WHERE CUSTOMER_ID = 1;

SHOW STREAMS LIKE 'CUSTOMER_STREAM';
DESCRIBE STREAM CUSTOMER_STREAM;
SELECT * FROM CUSTOMER_STREAM;

INSERT INTO AUDIT_CUSTOMERS
SELECT * FROM CUSTOMER_STREAM;

===============================

--APPEND ONLY STREAMS
CREATE OR REPLACE TABLE LOCATIONS (
    LOCATION_ID NUMBER,
    CITY STRING,
    COUNTRY STRING
);

CREATE OR REPLACE STREAM LOCATION_APPEND_STREAM
ON TABLE LOCATIONS
APPEND_ONLY = TRUE;

SELECT *
FROM LOCATIONS;

INSERT INTO LOCATIONS VALUES
(8, 'UDUPI', 'India');

SELECT *
FROM LOCATION_APPEND_STREAM;

UPDATE LOCATIONS
SET CITY = 'Bengaluru'
WHERE LOCATION_ID = 8;

DELETE FROM LOCATIONS
WHERE LOCATION_ID = 8;


INSERT INTO AUDIT_LOCATION 
SELECT *
FROM LOCATION_APPEND_STREAM;
========================================================================
